In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('C:/Users/ishan/Documents/Data Science Projects/Data Science/Deep Learning/ANN Churn Modelling/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X = df.iloc[:,3:13]
y= df.iloc[:,13]

In [8]:
geography = pd.get_dummies(X['Geography'], drop_first= True)
gender = pd.get_dummies(X['Gender'], drop_first= True)

In [9]:
X = pd.concat([X, geography, gender], axis = 1)
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0          1               1        101348.88        0      0     0  
1          0               1        112542.58        0      1     0  
2          1               0        113931.57        0      0     0  
3          0               0         93826.63        0      0     0  
4          1               1         79084.10        0      1     0

In [10]:
X = X.drop(['Geography', 'Gender'] , axis = 1)
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size= 0.2, random_state= 42)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ModuleNotFoundError: No module named 'keras'

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU, PReLU, ELU
from keras.layers import Dropout

In [26]:
classifier = Sequential()

In [27]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 10, kernel_initializer = 'he_uniform',activation='relu',input_dim = 11))
classifier.add(Dropout(0.3))

# Adding the second hidden layer
classifier.add(Dense(units = 10, kernel_initializer = 'he_uniform',activation='relu'))
classifier.add(Dropout(0.3))
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer  = 'glorot_uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
model_history=classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, epochs = 100)


Epoch 1/100
536/536 [==============================] - 2s 3ms/step - loss: 0.6658 - accuracy: 0.7292 - val_loss: 0.5347 - val_accuracy: 0.7872
Epoch 2/100
536/536 [==============================] - 1s 3ms/step - loss: 0.6037 - accuracy: 0.7628 - val_loss: 0.5072 - val_accuracy: 0.7887
Epoch 3/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7753 - val_loss: 0.4923 - val_accuracy: 0.7902
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7905 - val_loss: 0.4834 - val_accuracy: 0.7910
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7808 - val_loss: 0.4760 - val_accuracy: 0.7906
Epoch 6/100
536/536 [==============================] - 1s 3ms/step - loss: 0.5094 - accuracy: 0.7961 - val_loss: 0.4715 - val_accuracy: 0.7906
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7904 - val_loss: 0.4664 - val_accuracy: 0.7910

Epoch 58/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4204 - accuracy: 0.8217 - val_loss: 0.4218 - val_accuracy: 0.8289
Epoch 59/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4188 - accuracy: 0.8150 - val_loss: 0.4217 - val_accuracy: 0.8289
Epoch 60/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4067 - accuracy: 0.8306 - val_loss: 0.4208 - val_accuracy: 0.8304
Epoch 61/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4206 - accuracy: 0.8197 - val_loss: 0.4197 - val_accuracy: 0.8296
Epoch 62/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4316 - accuracy: 0.8098 - val_loss: 0.4197 - val_accuracy: 0.8300
Epoch 63/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4190 - accuracy: 0.8144 - val_loss: 0.4184 - val_accuracy: 0.8292
Epoch 64/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4234 - accuracy: 0.8159 - val_loss: 0.4181 - val_accuracy:

In [28]:
y_pred = classifier.predict(X_test)
y_pred

array([[0.07368463],
       [0.06470484],
       [0.26559013],
       ...,
       [0.5769693 ],
       [0.10146669],
       [0.2654347 ]], dtype=float32)

In [29]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [23]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [30]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1583,   24],
       [ 279,  114]], dtype=int64)

In [31]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
score

# We got accuracy of 0.85 when we didn't used Dropout
# We got accuracy of 0.8485 when we used Dropout 

0.8485